### ISSUE TITLE
PA Review: Likes

### ISSUE THREAD

**Issue by bergieboy** [bergieboy/printstagram#12]
- [x] Backend: DB, model, controller, views
 - [x]  Redux Loop: ajax, actions, reducer
  - [x] Presentational Components
  - [ ] Styling
  - [x] Smooth, bug-free navigation
  - [x] Adequate and appropriate seeds

**Comment by xnanodax** [comment]
Let's finish up some styling before we close this :)

|instagram | printstagram |
|--|--|
| ![screen shot 2018-04-13 at 9 16 52 am](https://user-images.githubusercontent.com/20424731/38746155-854e4ebe-3efb-11e8-8bf1-ea7129189640.png)|![screen shot 2018-04-13 at 9 16 57 am](https://user-images.githubusercontent.com/20424731/38746158-87f0f5cc-3efb-11e8-9a9f-8ba93d8408df.png)|

**Comment by bergieboy** [comment]
Added comments which focuses you to the add comment input field!
