### ISSUE TITLE
PA Review: Photos

### ISSUE THREAD

**Issue by bergieboy** [bergieboy/printstagram#13]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by xnanodax** [comment]
- [x] Currently experiencing a 500 level error when uploading photos. Oh! Didn't experience the error again.
