### ISSUE TITLE
DB Schema

### ISSUE THREAD

**Issue by xnanodax** [bergieboy/printstagram#3]
# Database Schema
- [x] Contains correct datatypes
- [x] Contains appropriate constraints/details
    - [x] primary key
    - [x] not null
    - [x] unique
      - [x] I would add a unique constraint on the user_id and photo_id so the combination only shows up once on joins table. 
    - [x] indexed
    - [x] foreign key
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made

- [x] Correctly formatted
    - [x] schema is written in a table format
    - [x] column names are bolded
    - [x] columns names are lowercased and snaked_cased

# Comments:
I would add `created_at` and `updated_at` to your user_followers page.
I would add a location field onto photos since instagram does that.

**Comment by xnanodax** [comment]
Initial Proposal for this page has been reviewed.

**Comment by bergieboy** [comment]
I added the unique constraints to `user_id` and `photo_id` for likes only. I think that's what you meant. I also added `created_at` and `updated_at` to the followers table.

**Comment by xnanodax** [comment]
Awesome!
