### ISSUE TITLE
Routes

### ISSUE THREAD

**Issue by xnanodax** [bergieboy/printstagram#4]
# Routes

- [x] Routes accurately reflect MVPs and Component Hierarchy
- [x] Covers the frontend functionality of the site through routes that match to the wireframes
- [x] Contains the following sections: HTML, API Endpoints(Backend), and Frontend Routes
- [x] Each route has a description
- [x] API Endpoint routes contains wildcard variables written in `snake_case`
- [x] Frontend routes contains wildcard variables written in `camelCase`
- [x] Routes does not contain [superfluous routes](https://github.com/appacademy/curriculum/blob/master/rails/readings/routing-part-ii.md)
  - Note: I would double check your route for deleting a like. You wont need the reference the photo id.
- [x] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
    + probably doesn't need a `GET likes` api endpoint bc that info comes through the post show
- [x] Correctly formatted
    - [x] Routes are displayed with `inline coding text` (backticks)

# Comments:
- [x] Add PATCH route to the first comment of a photo.

**Comment by xnanodax** [comment]
Initial Proposal for this page has been reviewed.

**Comment by bergieboy** [comment]
Updated route to `DELETE /api/likes/:id`

**Comment by xnanodax** [comment]
Add a patch route to the first comment of a photo. After that, we are done with this wiki issue!

**Comment by xnanodax** [comment]
Awesome I see you added that route. Just a friendly reminder that that route should only allow first comment of each photo to be editable.
