### ISSUE TITLE
Sample State

### ISSUE THREAD

**Issue by xnanodax** [bergieboy/printstagram#5]
# Sample State
- [x] State shape is flat!
- [x] State's keys are camelCased
- [x] All keys within the values in the state are accessible in the schema (Ex: if you create a `img_url` key in the state, make sure your database also has a column that contains an `img_url`)
- [x] Correctly formatted
    - [x] Sample state is rendered with 3 back ticks before and after. This will display the state as a code block instead of a giant line of text
    - [x] Top level slices
        - [x] `entities`
        - [x] `session`
        - [x] `errors` (here or in `ui`)
        - [x] `ui` (if needed)
    - [x] Should NOT have nested slices, aka  `comments` inside of `posts`
      + Some info from other tables is ok, for instance:
        + the author username and imageurl for a post. basically any info that the user can't change
        + like count and a boolean on whether the user likes the post instead of a likes slice
    
# Comments:
-  [x] In your user slice of state, you may just want to record who a user follows instead of the photo ids they have liked. 
- [x] You may want to reference comment ids on the photos slice of state. it'll be easier to iterate through that array instead of searching for comments that have a specific image id.

**Comment by xnanodax** [comment]
Initial Proposal for this page has been reviewed.

**Comment by bergieboy** [comment]
Added comment Ids to the photo slice of state. I also added followers to the user slice of state - can we discuss this one later today, so have a better understanding of what you mean?

**Comment by xnanodax** [comment]
Yes, we can! I think the current state has a user that is following themselves. Is this a function in Instagram?

**Comment by bergieboy** [comment]
lol no, I was quickly throwing in identical arrays. sry.

**Comment by xnanodax** [comment]
reminder!
- [ ] Sample followers in user's slice of state. 
- [ ] Sample users' likes in photos slice of state.

Awesome!
