### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by bergieboy** [bergieboy/printstagram#8]
- [x]  Backend: DB, model, controller, views
 - [x]  Redux Loop: ajax, actions, reducer
 - [x]  Presentational Components
- [x]   Demo User Added
- [x]   Styling
- [x]  Smooth, bug free navigation
  - [x]  Login errors clears when switching from login form to sign up form (and vice-versa)
- [x]   Adequate and appropriate seeds

**Comment by xnanodax** [comment]
- [x] When logging in with demo using, I receive a level 500 error.

- [x] When logging in with invalid credentials or with the demo login, I see the following error:
![screen shot 2018-04-06 at 3 47 59 pm](https://user-images.githubusercontent.com/20424731/38447412-fb789b02-39b1-11e8-9758-b20d42b2c8a2.png)

**Comment by xnanodax** [comment]
- [x] Going to a random route `/#/oweiniouewbrviuwebv` should redirect to either `/`, `/login`, or `/signup`
- [x] There is a flicker of an session error when I am logging into the demo user account.
![screen shot 2018-04-11 at 3 29 10 pm 1](https://user-images.githubusercontent.com/20424731/38646516-1fe2f48a-3d9d-11e8-82bb-073c2d5035bf.png)

**Comment by bergieboy** [comment]
I don't know how to get it to not display the errors, can we discuss tomorrow?

**Comment by xnanodax** [comment]
Gotcha Yes :)!
